package test

import "backend/models"

var Forms = []models.Encuestas{
	{
		UsuarioId:                   1,
		Estado_financiamiento:       0,
		Moneda:                      "PEN",
		Fecha_de_inicio_de_Proyecto: "1/5/2022",
		Centro_de_Investigación:     "Centro de investigación en bioingeniería - BIO",
		Departamento_Academico:      "Bioingeniería",
		Titulo_de_Proyecto:          "Investigación de celulas cancerigenas usando Python",
		Linea_de_investigacion:      "Investigación Médica",
		Coeinvestigadores_de_UTEC:   "Daniel Rosa",
		Investigador_Principal:      "Rosario Ponce",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "abc123@email.com",
		Overhead:                    0,
		Presupuesto_proyecto:        100,
		Tipo_entidad_financiadora:   "Financiamiento interno (UTEC)",
		Monto_asignado:              10000,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "aprobado",
	},
	{
		UsuarioId:                   1,
		Estado_financiamiento:       1,
		Moneda:                      "PEN",
		Fecha_de_inicio_de_Proyecto: "5/7/2022",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Ciencias de la computación",
		Titulo_de_Proyecto:          "Redes Neuronales",
		Linea_de_investigacion:      "Machine Learning",
		Coeinvestigadores_de_UTEC:   "Luis Chavez",
		Investigador_Principal:      "Javier Lozada",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "abc123@email.com",
		Overhead:                    0,
		Presupuesto_proyecto:        4000,
		Tipo_entidad_financiadora:   "Financiamiento interno (UTEC)",
		Monto_asignado:              8000,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "aprobado",
	},
	{
		UsuarioId:                   2,
		Estado_financiamiento:       0,
		Moneda:                      "PEN",
		Fecha_de_inicio_de_Proyecto: "25/06/2022",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Ciencias de la computación",
		Titulo_de_Proyecto:          "Simulación de choques de automoviles usando Algoritmos de Machine Learning",
		Linea_de_investigacion:      "Machine Learning",
		Coeinvestigadores_de_UTEC:   "Solange Del Solar",
		Investigador_Principal:      "Gabriela Pereira",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "abc123@email.com",
		Overhead:                    0,
		Presupuesto_proyecto:        5000,
		Tipo_entidad_financiadora:   "Financiamiento interno (UTEC)",
		Monto_asignado:              9000,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "aprobado",
	},
	{
		UsuarioId:                   2,
		Estado_financiamiento:       0,
		Moneda:                      "PEN",
		Fecha_de_inicio_de_Proyecto: "14/11/2021",
		Centro_de_Investigación:     "Centro de investigación en bioingeniería - BIO",
		Departamento_Academico:      "Bioingeniería",
		Titulo_de_Proyecto:          "Análisis de Carcinomas usando algoritmos de Marchine Learning",
		Linea_de_investigacion:      "Investigación Médica",
		Coeinvestigadores_de_UTEC:   "Carlos Guevara",
		Investigador_Principal:      "Raul Montes",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "abc123@email.com",
		Overhead:                    0,
		Presupuesto_proyecto:        3000,
		Tipo_entidad_financiadora:   "Financiamiento interno (UTEC)",
		Monto_asignado:              10000,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "aprobado",
	},
	{UsuarioId: 5,
		Estado_financiamiento:       0,
		Moneda:                      "GBP",
		Fecha_de_inicio_de_Proyecto: "01/24/2017",
		Centro_de_Investigación:     "Otro",
		Departamento_Academico:      "CE2A",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Patrimonio",
		Coeinvestigadores_de_UTEC:   "Silvia Lavandera Ponce",
		Investigador_Principal:      "Julio Ernesto Valdivia Silva",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        11916,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              4894,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 4,
		Estado_financiamiento:       1,
		Moneda:                      "CHF",
		Fecha_de_inicio_de_Proyecto: "01/19/2017",
		Centro_de_Investigación:     "Centro de investigación y tecnología del agua - CITA",
		Departamento_Academico:      "Otro",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Materiales y Sistemas Constructivos",
		Coeinvestigadores_de_UTEC:   "Fabien Yves Paul Cornillier",
		Investigador_Principal:      "Alfredo Cardenas Rivera",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10763,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              3149,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 5,
		Estado_financiamiento:       1,
		Moneda:                      "EUR",
		Fecha_de_inicio_de_Proyecto: "01/14/2017",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Ingeniería Ambiental",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Agua y Medio Ambiente",
		Coeinvestigadores_de_UTEC:   "Hermes Yesser Pantoja Carhuavilca",
		Investigador_Principal:      "Harry Saavedra Espinoza",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9951,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              4581,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 5,
		Estado_financiamiento:       0,
		Moneda:                      "PEN",
		Fecha_de_inicio_de_Proyecto: "01/11/2017",
		Centro_de_Investigación:     "Centro de investigación y tecnología del agua - CITA",
		Departamento_Academico:      "Ingeniería Ambiental",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Agua y Medio Ambiente",
		Coeinvestigadores_de_UTEC:   "Ernesto Cuadros Vargas",
		Investigador_Principal:      "Luis Ernesto Flores Olazo",
		Tipo_de_participacion:       "Otro",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10903,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              3162,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 2,
		Estado_financiamiento:       1,
		Moneda:                      "PEN",
		Fecha_de_inicio_de_Proyecto: "01/07/2017",
		Centro_de_Investigación:     "No aplica",
		Departamento_Academico:      "HACS",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Patrimonio",
		Coeinvestigadores_de_UTEC:   "Andrés Arias Moreno",
		Investigador_Principal:      "Isaac Santiago Robles Rodriguez",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        11754,
		Tipo_entidad_financiadora:   "Fondo concursable externo (RFP)",
		Monto_asignado:              4645,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 1,
		Estado_financiamiento:       1,
		Moneda:                      "EUR",
		Fecha_de_inicio_de_Proyecto: "01/02/2017",
		Centro_de_Investigación:     "Centro de investigación y tecnología del agua - CITA",
		Departamento_Academico:      "Ciencia de la computación",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Patrimonio",
		Coeinvestigadores_de_UTEC:   "Paul Antonio Cardenas Lizana",
		Investigador_Principal:      "Luis Alberto Bedriñana Mera",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9650,
		Tipo_entidad_financiadora:   "Fondo concursable externo (RFP)",
		Monto_asignado:              3938,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 1,
		Estado_financiamiento:       0,
		Moneda:                      "GBP",
		Fecha_de_inicio_de_Proyecto: "01/01/2017",
		Centro_de_Investigación:     "Centro de investigación en bioingeniería - BIO",
		Departamento_Academico:      "Ingeniería Electrónica",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Agua y Medio Ambiente",
		Coeinvestigadores_de_UTEC:   "Lei Zhang",
		Investigador_Principal:      "Julio Ernesto Valdivia Silva",
		Tipo_de_participacion:       "Otro",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10361,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              3783,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 3,
		Estado_financiamiento:       0,
		Moneda:                      "EUR",
		Fecha_de_inicio_de_Proyecto: "01/06/2017",
		Centro_de_Investigación:     "Otro",
		Departamento_Academico:      "Ingeniería Mecánica",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Patrimonio",
		Coeinvestigadores_de_UTEC:   "Gabriel Percy Micchue Vela",
		Investigador_Principal:      "Jose Gerardo Deustua Rossel",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10280,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              4853,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 3,
		Estado_financiamiento:       1,
		Moneda:                      "PEN",
		Fecha_de_inicio_de_Proyecto: "01/21/2017",
		Centro_de_Investigación:     "Centro de investigación en bioingeniería - BIO",
		Departamento_Academico:      "Ciencia de la computación",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Patrimonio",
		Coeinvestigadores_de_UTEC:   "Jorge Luis Gonzales Reaño",
		Investigador_Principal:      "César Rolando Nunura Nunura",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9186,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              4759,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 5,
		Estado_financiamiento:       1,
		Moneda:                      "CHF",
		Fecha_de_inicio_de_Proyecto: "01/15/2017",
		Centro_de_Investigación:     "Centro de investigación en bioingeniería - BIO",
		Departamento_Academico:      "Ciencias",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Bioingeniería",
		Coeinvestigadores_de_UTEC:   "Daniel Vicente Horna Muñoz",
		Investigador_Principal:      "Gabriela Pella Fernández",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10968,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              3695,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Investigación y desarrollo (original research)",
	},
	{UsuarioId: 1,
		Estado_financiamiento:       0,
		Moneda:                      "CHF",
		Fecha_de_inicio_de_Proyecto: "01/20/2017",
		Centro_de_Investigación:     "Centro de impacto y responsabilidad social - CIRSO",
		Departamento_Academico:      "Ingeniería Industrial",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Administrativas y Económicas",
		Coeinvestigadores_de_UTEC:   "Jose Gerardo Deustua Rossel",
		Investigador_Principal:      "Arturo Rojas Moreno",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9349,
		Tipo_entidad_financiadora:   "Fondo concursable externo (RFP)",
		Monto_asignado:              3742,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Investigación y desarrollo (original research)",
	},
	{UsuarioId: 4,
		Estado_financiamiento:       1,
		Moneda:                      "EUR",
		Fecha_de_inicio_de_Proyecto: "01/04/2017",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Bioingeniería",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Agua y Medio Ambiente",
		Coeinvestigadores_de_UTEC:   "Samuel Charca Mamani",
		Investigador_Principal:      "Rafael Ivan Vera Pomalaza",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10581,
		Tipo_entidad_financiadora:   "Fondo concursable externo (RFP)",
		Monto_asignado:              4761,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 4,
		Estado_financiamiento:       0,
		Moneda:                      "GBP",
		Fecha_de_inicio_de_Proyecto: "01/13/2017",
		Centro_de_Investigación:     "Centro de investigación en bioingeniería - BIO",
		Departamento_Academico:      "Bioingeniería",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Ingeniería y Tecnlología",
		Coeinvestigadores_de_UTEC:   "Wangdo Kim",
		Investigador_Principal:      "Andrea Karina Gonzales Lombardi",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9019,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              3214,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 2,
		Estado_financiamiento:       1,
		Moneda:                      "EUR",
		Fecha_de_inicio_de_Proyecto: "01/24/2017",
		Centro_de_Investigación:     "Otro",
		Departamento_Academico:      "Ingeniería Mecatrónica",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Impacto y Responsabilidad Social",
		Coeinvestigadores_de_UTEC:   "Harry Saavedra Espinoza",
		Investigador_Principal:      "Gabriel Percy Micchue Vela",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9917,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              4652,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 4,
		Estado_financiamiento:       1,
		Moneda:                      "USD",
		Fecha_de_inicio_de_Proyecto: "01/15/2017",
		Centro_de_Investigación:     "No aplica",
		Departamento_Academico:      "Ingeniería Civil",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Computación Sostenible",
		Coeinvestigadores_de_UTEC:   "Claudia Fausta Antonini Bova",
		Investigador_Principal:      "Tulio Antonio Antezano Inga",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9854,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              3676,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 5,
		Estado_financiamiento:       0,
		Moneda:                      "CHF",
		Fecha_de_inicio_de_Proyecto: "01/24/2017",
		Centro_de_Investigación:     "Centro de investigación y tecnología del agua - CITA",
		Departamento_Academico:      "Ingeniería Mecatrónica",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Bioingeniería",
		Coeinvestigadores_de_UTEC:   "Roberto Sumiyoshi Furukawa Fukuda",
		Investigador_Principal:      "Mayu Alberto Tincopa Heredia",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9599,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              4542,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 2,
		Estado_financiamiento:       1,
		Moneda:                      "Otro",
		Fecha_de_inicio_de_Proyecto: "01/13/2017",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Ingeniería Industrial",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Agua y Medio Ambiente",
		Coeinvestigadores_de_UTEC:   "Isabel Quintana Cobo",
		Investigador_Principal:      "Diana Castillo",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9067,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              4693,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Investigación y desarrollo (original research)",
	},
	{UsuarioId: 4,
		Estado_financiamiento:       1,
		Moneda:                      "CHF",
		Fecha_de_inicio_de_Proyecto: "01/07/2017",
		Centro_de_Investigación:     "Centro de investigación y tecnología del agua - CITA",
		Departamento_Academico:      "Ciencia de la computación",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Computación Sostenible",
		Coeinvestigadores_de_UTEC:   "Gabriela Pella Fernández",
		Investigador_Principal:      "Isabel Quintana Cobo",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10177,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              4901,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Investigación y desarrollo (original research)",
	},
	{UsuarioId: 5,
		Estado_financiamiento:       0,
		Moneda:                      "CHF",
		Fecha_de_inicio_de_Proyecto: "01/14/2017",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Ingeniería Mecánica",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Ingeniería y Tecnlología",
		Coeinvestigadores_de_UTEC:   "Oscar Efraín Ramos Ponce",
		Investigador_Principal:      "Wangdo Kim",
		Tipo_de_participacion:       "Entidad Asociada",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9655,
		Tipo_entidad_financiadora:   "Fondo concursable externo (RFP)",
		Monto_asignado:              4217,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Investigación y desarrollo (original research)",
	},
	{UsuarioId: 4,
		Estado_financiamiento:       1,
		Moneda:                      "GBP",
		Fecha_de_inicio_de_Proyecto: "01/01/2017",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Ingeniería Química",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Patrimonio",
		Coeinvestigadores_de_UTEC:   "Alfredo Cardenas Rivera",
		Investigador_Principal:      "Andrés Arias Moreno",
		Tipo_de_participacion:       "Otro",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        11389,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              3772,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 1,
		Estado_financiamiento:       0,
		Moneda:                      "CHF",
		Fecha_de_inicio_de_Proyecto: "01/28/2017",
		Centro_de_Investigación:     "Centro de impacto y responsabilidad social - CIRSO",
		Departamento_Academico:      "Ingeniería Civil",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Administrativas y Económicas",
		Coeinvestigadores_de_UTEC:   "Julio Ernesto Valdivia Silva",
		Investigador_Principal:      "Giancarlo Marcone Flores",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9935,
		Tipo_entidad_financiadora:   "Fondo concursable externo (RFP)",
		Monto_asignado:              4700,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Otro",
	},
	{UsuarioId: 2,
		Estado_financiamiento:       1,
		Moneda:                      "Otro",
		Fecha_de_inicio_de_Proyecto: "01/17/2017",
		Centro_de_Investigación:     "Centro de investigación en bioingeniería - BIO",
		Departamento_Academico:      "Ingeniería Mecánica",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Bioingeniería",
		Coeinvestigadores_de_UTEC:   "Antonio Marty Quispe Gutiérrez",
		Investigador_Principal:      "Juan Carlos Bueno Villanueva",
		Tipo_de_participacion:       "Otro",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        11839,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              3964,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 1,
		Estado_financiamiento:       1,
		Moneda:                      "GBP",
		Fecha_de_inicio_de_Proyecto: "01/27/2017",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Bioingeniería",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Ingeniería y Tecnlología",
		Coeinvestigadores_de_UTEC:   "Victor Manuel Murray Herrera",
		Investigador_Principal:      "Ursula Rodriguez Zúniga",
		Tipo_de_participacion:       "Otro",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        10468,
		Tipo_entidad_financiadora:   "Fondo con empresas (Business)Financiamiento interno (UTEC)",
		Monto_asignado:              4710,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 1,
		Estado_financiamiento:       0,
		Moneda:                      "USD",
		Fecha_de_inicio_de_Proyecto: "01/17/2017",
		Centro_de_Investigación:     "Centro de investigación en computación sustentable - COMPSUST",
		Departamento_Academico:      "Ingeniería Civil",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Energía y Minas",
		Coeinvestigadores_de_UTEC:   "Wilson Alexander Hormaza Rodríguez",
		Investigador_Principal:      "Victor Manuel Murray Herrera",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        11021,
		Tipo_entidad_financiadora:   "Fondo concursable externo (RFP)",
		Monto_asignado:              4078,
		Se_requiere_aprovacion:      false,
		Tipo_de_Proyecto:            "Actividad de extensión o capacitación (extension activity)",
	},
	{UsuarioId: 5,
		Estado_financiamiento:       1,
		Moneda:                      "EUR",
		Fecha_de_inicio_de_Proyecto: "01/16/2017",
		Centro_de_Investigación:     "Centro de investigación de cemento y concreto - CICC",
		Departamento_Academico:      "Ingeniería Mecánica",
		Titulo_de_Proyecto:          "XD",
		Linea_de_investigacion:      "Excelencia en Enseñanza y Aprendizaje",
		Coeinvestigadores_de_UTEC:   "Alejandro Cristians Ríos Cuadros",
		Investigador_Principal:      "Isaac Santiago Robles Rodriguez",
		Tipo_de_participacion:       "Entidad Solicitante",
		POI_Financiadora:            "Fondo Semilla",
		Overhead:                    0,
		Presupuesto_proyecto:        9857,
		Tipo_entidad_financiadora:   "Otro",
		Monto_asignado:              4675,
		Se_requiere_aprovacion:      true,
		Tipo_de_Proyecto:            "Otro",
	},
}
